### ISSUE TITLE
default FAILURESTRINGS matches words that contains BUG reporting false failures

### ISSUE THREAD

**Issue by bgoncalv** [restraint-harness/restraint#273]
`FAILURESTRINGS="Oops|BUG|NMI appears to be stuck|Badness at"`

This cause dmesg check to report failure if it finds things like

```
[ 3926.374636] EDAC DEBUG: ie31200_check: MC0
```

**Comment by bgoncalv** [comment]
would make sense to update the variable to use something like `"\bOops\b|\bBUG\b|NMI appears to be stuck|Badness at"` ?

**Comment by idorax** [comment]
@bgoncalv, `\bOops\b|\bBUG\b|NMI appears to be stuck|Badness at` looks good to fix this issue, I'll file the PR soon :-)

**Comment by idorax** [comment]
Hi @bgoncalv, @cbouchar,  I don't have permissions to close this issue. Would you please help to close it? Thanks! (For more, please refer to https://github.com/restraint-harness/restraint/pull/278)
