### ISSUE TITLE
add restraint-rhts to CentOSStream9 repo

### ISSUE THREAD

**Issue by bgoncalv** [restraint-harness/restraint#306]
The https://beaker-project.org/yum/harness/CentOSStream9/ repo is missing restraint-rhts. 

This package is available, for example, on Rawhide (https://beaker-project.org/yum/harness/FedoraRawhide).

I'm not sure if this is the right place to request this, but it would be great if CentOSStream9 repo could have this package.

**Comment by bgoncalv** [comment]
@StykMartin @cbouchar would you be able to help here?

**Comment by StykMartin** [comment]
I can try to build it and see how it goes.

**Comment by cbouchar** [comment]
@bgoncalv FYI CentOSStream9 is available downstream.

**Comment by mh21** [comment]
> @bgoncalv FYI CentOSStream9 is available downstream.

yes, this is for a test run in restraint standalone mode without RH intranet access

**Comment by StykMartin** [comment]
Restraint RHTS is available for CentOS Stream 9.
