### ISSUE TITLE
Package restraint for Fedora 40

### ISSUE THREAD

**Issue by mh21** [restraint-harness/restraint#316]
Fedora 40 is released 🎉.

Would it be possible to update the DNF repos at https://beaker-project.org/yum/harness/ to include FC40?

On a more general note, is there a reason restraint is not included in the official Fedora repos similar to the beaker client?

**Comment by StykMartin** [comment]
I am not sure if we can rebuild it right now with additional changes being done in build root for FC40. We need to do a new release with patches from @danrodrig. 

Restraint is not in the official Fedora repositories because Restraint will not pass the Fedora review right now. There is a pretty significant list of things that need to be changed to even think about pushing it there. Some of these changes are certainly breaking changes.

**Comment by mh21** [comment]
ack; do you think it would be feasible to setup Packit similar to what is present for [beaker](https://github.com/beaker-project/beaker/blob/python-3/.packit.yaml)?

**Comment by StykMartin** [comment]
So the Packit setup already [exists](https://github.com/restraint-harness/restraint/blob/master/.packit.yaml), but it is a suboptimal experience. Right now, it is dynamically linked against the spec I created specifically for Fedora, with no static linking - which is the opposite of what we are trying to achieve with the current builds being used in production. 

The goal of this was to validate Restraint against the latest build root, but I wouldn't recommend people use it as there is no heavy testing involved - yet. 

However, what we can do, is to replicate what I did for beaker [here](https://github.com/beaker-project/beaker/blob/python-3/.github/workflows/publish.yml)

**Comment by StykMartin** [comment]
We agreed at the community meeting yesterday that I will create a new release and build for all targets. I will prepare this over the weekend @mh21

**Comment by StykMartin** [comment]
I create a new release for Restraint to allow builds with newer Fedora. Everything has been promoted to YUM repositories in BP.org.
You can find Restraint 0.4.5 in the following repositories
- Fedora Rawhide
- Fedora 40
- Fedora 39
- CentOS Stream 9
